### ISSUE TITLE
Add validation for addresses in Reserved tokens

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/ico-wizard#285]
Unhandled rejection Error: Provided address ": 0xA1Ff7372f7f28f527CE6A96AC84fa70d1D101897" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
    at Object._ [as inputAddressFormatter] (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1047077)
    at a._inputFormatter (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1226814)
    at a.o.encode (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:160711)
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:160548
    at Array.forEach (<anonymous>)
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:160519
    at a.o.encode (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:160565)
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:441804
    at Array.map (<anonymous>)
    at m.encodeParameters (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:441777)
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1449958
    at Array.map (<anonymous>)
    at Object.h._encodeMethodABI (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1449933)
    at Object.h._processExecuteArguments (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1454024)
    at Object.h._executeMethod (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1454515)
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:342307
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:145946
From previous event:
    at i.d [as _captureStackTrace] (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1074065)
    at i._then (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1103415)
    at i.then (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1101783)
    at l (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:145546)
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:338741
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:145946
    at a (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1134338)
    at i._settlePromiseFromHandler (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1107781)
    at i._settlePromise (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1108625)
    at i._settlePromise0 (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1109327)
    at i._settlePromises (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1110697)
    at https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1066371
    at MutationObserver.<anonymous> (https://wizard-stage.oracles.org/static/js/main.338d1567.js:1:1124290)

**Comment by fvictorio** [comment]
We have two options here:

1. Convert the address to lower case, to circumvent the validation. Easier to do, but less safe.
2. Validate the address. It's not hard to do, but it implies adding the `ethereumjs-util` package, that will increase the size of the bundle (not a big deal IMO, but I don't know how much you care about that).

I'll start working on option 2, but let me know if you prefer to go with 1.

More info about address validation:
- https://ethereum.stackexchange.com/questions/1374/how-can-i-check-if-an-ethereum-address-is-valid
- https://ethereum.stackexchange.com/questions/267/why-dont-ethereum-addresses-have-checksums
- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by vbaranov** [comment]
>Validate the address. It's not hard to do, but it implies adding the ethereumjs-util package, that will increase the size of the bundle (not a big deal IMO, but I don't know how much you care about that).

Why not to use `web.utils.isAddress`? So, we don't need any additional package for this

**Comment by fvictorio** [comment]
Oh, I missed that function. Thanks!

**Comment by vbaranov** [comment]
@fvictorio can we close it?

**Comment by fvictorio** [comment]
Yes, sorry, I forgot to reference it in the PR.

Fixed in #378.
